baseURL = "https://mnoukhov.github.io/"
languageCode = "en-us"
title = "Michael Noukhovitch"
theme = "hugo-tufte"
canonifyURLs = true

[pagination]
pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[params]
marginNoteInd = "âŠ•"
showPoweredBy = false
showSummary = true
hidedate = false
math = false
KaTeXVersion = "0.16.4"
KaTeXCDN = "//cdn.jsdelivr.net/npm"
centerArticle = false
sansSubtitle = false
favicon = "favicon_32x32.png"
touchicon = "touch-icon.png"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.nav]]
name = "Blog"
identifier = "posts"
url = "/posts/"
weight = -90
